# client-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: hermes-broker
spec:
  type: ClusterIP
  selector:
    app: hermes
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http
      port: 8080
      targetPort: 8080