// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID        string `json:"id"`
	Topic     string `json:"topic"`
	Payload   string `json:"payload"`
	Timestamp int32  `json:"timestamp"`
}

type Mutation struct {
}

type PublishResponse struct {
	Success bool `json:"success"`
}

type Query struct {
}

type Subscription struct {
}
