// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/broker.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliveryMode int32

const (
	DeliveryMode_CONSISTENT  DeliveryMode = 0 // Synchronous Raft (Slow, Safe)
	DeliveryMode_EVENTUAL    DeliveryMode = 1 // Synchronous Local Disk + Asynchronous Replication (Fast, Durable on Crash)
	DeliveryMode_PERFORMANCE DeliveryMode = 2 // Synchronous Memory + Asynchronous Disk/Replica (Extremely Fast, Risk of Crash)
)

// Enum value maps for DeliveryMode.
var (
	DeliveryMode_name = map[int32]string{
		0: "CONSISTENT",
		1: "EVENTUAL",
		2: "PERFORMANCE",
	}
	DeliveryMode_value = map[string]int32{
		"CONSISTENT":  0,
		"EVENTUAL":    1,
		"PERFORMANCE": 2,
	}
)

func (x DeliveryMode) Enum() *DeliveryMode {
	p := new(DeliveryMode)
	*p = x
	return p
}

func (x DeliveryMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliveryMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_broker_proto_enumTypes[0].Descriptor()
}

func (DeliveryMode) Type() protoreflect.EnumType {
	return &file_proto_broker_proto_enumTypes[0]
}

func (x DeliveryMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliveryMode.Descriptor instead.
func (DeliveryMode) EnumDescriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{0}
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // Raw binary data (serialized JSON or anything else)
	Mode          DeliveryMode           `protobuf:"varint,3,opt,name=mode,proto3,enum=broker.DeliveryMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_proto_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{0}
}

func (x *PublishRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PublishRequest) GetMode() DeliveryMode {
	if x != nil {
		return x.Mode
	}
	return DeliveryMode_CONSISTENT
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_proto_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{1}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type PublishSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedCount uint64                 `protobuf:"varint,1,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	FailedCount    uint64                 `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishSummary) Reset() {
	*x = PublishSummary{}
	mi := &file_proto_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSummary) ProtoMessage() {}

func (x *PublishSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSummary.ProtoReflect.Descriptor instead.
func (*PublishSummary) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{2}
}

func (x *PublishSummary) GetProcessedCount() uint64 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *PublishSummary) GetFailedCount() uint64 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

type PublishBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payloads      [][]byte               `protobuf:"bytes,2,rep,name=payloads,proto3" json:"payloads,omitempty"` // Array de payloads
	Mode          DeliveryMode           `protobuf:"varint,3,opt,name=mode,proto3,enum=broker.DeliveryMode" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishBatchRequest) Reset() {
	*x = PublishBatchRequest{}
	mi := &file_proto_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishBatchRequest) ProtoMessage() {}

func (x *PublishBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishBatchRequest.ProtoReflect.Descriptor instead.
func (*PublishBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{3}
}

func (x *PublishBatchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *PublishBatchRequest) GetPayloads() [][]byte {
	if x != nil {
		return x.Payloads
	}
	return nil
}

func (x *PublishBatchRequest) GetMode() DeliveryMode {
	if x != nil {
		return x.Mode
	}
	return DeliveryMode_CONSISTENT
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`                                     // Filled in only on the first package (Handshake)
	AckMessageId  string                 `protobuf:"bytes,2,opt,name=ack_message_id,json=ackMessageId,proto3" json:"ack_message_id,omitempty"` // Filled in when it is an ACK.
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`                                   // "SUBSCRIBE" or "ACK"
	GroupId       string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                  // Consumer Group
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{4}
}

func (x *SubscribeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeRequest) GetAckMessageId() string {
	if x != nil {
		return x.AckMessageId
	}
	return ""
}

func (x *SubscribeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SubscribeRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Message) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`       // Ex: "node-2"
	RaftAddr      string                 `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"` // Ex: "localhost:6001" (raft internal address)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_proto_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{6}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetRaftAddr() string {
	if x != nil {
		return x.RaftAddr
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_proto_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_broker_proto_rawDescGZIP(), []int{7}
}

func (x *JoinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_broker_proto protoreflect.FileDescriptor

const file_proto_broker_proto_rawDesc = "" +
	"\n" +
	"\x12proto/broker.proto\x12\x06broker\"j\n" +
	"\x0ePublishRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.broker.DeliveryModeR\x04mode\"+\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\x0ePublishSummary\x12'\n" +
	"\x0fprocessed_count\x18\x01 \x01(\x04R\x0eprocessedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x04R\vfailedCount\"q\n" +
	"\x13PublishBatchRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1a\n" +
	"\bpayloads\x18\x02 \x03(\fR\bpayloads\x12(\n" +
	"\x04mode\x18\x03 \x01(\x0e2\x14.broker.DeliveryModeR\x04mode\"\x81\x01\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12$\n" +
	"\x0eack_message_id\x18\x02 \x01(\tR\fackMessageId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\"g\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"C\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\traft_addr\x18\x02 \x01(\tR\braftAddr\">\n" +
	"\fJoinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error*=\n" +
	"\fDeliveryMode\x12\x0e\n" +
	"\n" +
	"CONSISTENT\x10\x00\x12\f\n" +
	"\bEVENTUAL\x10\x01\x12\x0f\n" +
	"\vPERFORMANCE\x10\x022\xc3\x02\n" +
	"\rBrokerService\x12:\n" +
	"\aPublish\x12\x16.broker.PublishRequest\x1a\x17.broker.PublishResponse\x12A\n" +
	"\rPublishStream\x12\x16.broker.PublishRequest\x1a\x16.broker.PublishSummary(\x01\x12D\n" +
	"\fPublishBatch\x12\x1b.broker.PublishBatchRequest\x1a\x17.broker.PublishResponse\x12:\n" +
	"\tSubscribe\x12\x18.broker.SubscribeRequest\x1a\x0f.broker.Message(\x010\x01\x121\n" +
	"\x04Join\x12\x13.broker.JoinRequest\x1a\x14.broker.JoinResponseB+Z)github.com/pedromedina19/hermes-broker/pbb\x06proto3"

var (
	file_proto_broker_proto_rawDescOnce sync.Once
	file_proto_broker_proto_rawDescData []byte
)

func file_proto_broker_proto_rawDescGZIP() []byte {
	file_proto_broker_proto_rawDescOnce.Do(func() {
		file_proto_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)))
	})
	return file_proto_broker_proto_rawDescData
}

var file_proto_broker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_broker_proto_goTypes = []any{
	(DeliveryMode)(0),           // 0: broker.DeliveryMode
	(*PublishRequest)(nil),      // 1: broker.PublishRequest
	(*PublishResponse)(nil),     // 2: broker.PublishResponse
	(*PublishSummary)(nil),      // 3: broker.PublishSummary
	(*PublishBatchRequest)(nil), // 4: broker.PublishBatchRequest
	(*SubscribeRequest)(nil),    // 5: broker.SubscribeRequest
	(*Message)(nil),             // 6: broker.Message
	(*JoinRequest)(nil),         // 7: broker.JoinRequest
	(*JoinResponse)(nil),        // 8: broker.JoinResponse
}
var file_proto_broker_proto_depIdxs = []int32{
	0, // 0: broker.PublishRequest.mode:type_name -> broker.DeliveryMode
	0, // 1: broker.PublishBatchRequest.mode:type_name -> broker.DeliveryMode
	1, // 2: broker.BrokerService.Publish:input_type -> broker.PublishRequest
	1, // 3: broker.BrokerService.PublishStream:input_type -> broker.PublishRequest
	4, // 4: broker.BrokerService.PublishBatch:input_type -> broker.PublishBatchRequest
	5, // 5: broker.BrokerService.Subscribe:input_type -> broker.SubscribeRequest
	7, // 6: broker.BrokerService.Join:input_type -> broker.JoinRequest
	2, // 7: broker.BrokerService.Publish:output_type -> broker.PublishResponse
	3, // 8: broker.BrokerService.PublishStream:output_type -> broker.PublishSummary
	2, // 9: broker.BrokerService.PublishBatch:output_type -> broker.PublishResponse
	6, // 10: broker.BrokerService.Subscribe:output_type -> broker.Message
	8, // 11: broker.BrokerService.Join:output_type -> broker.JoinResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_broker_proto_init() }
func file_proto_broker_proto_init() {
	if File_proto_broker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_broker_proto_rawDesc), len(file_proto_broker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_broker_proto_goTypes,
		DependencyIndexes: file_proto_broker_proto_depIdxs,
		EnumInfos:         file_proto_broker_proto_enumTypes,
		MessageInfos:      file_proto_broker_proto_msgTypes,
	}.Build()
	File_proto_broker_proto = out.File
	file_proto_broker_proto_goTypes = nil
	file_proto_broker_proto_depIdxs = nil
}
